project:
  type: website
  output-dir: docs

website:
  title: "kqlqkqlqF's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: index_zh.qmd
        text: 中文首页
      - href: about.qmd
        text: About

format:
  html:
    theme: yeti
    css: styles.css
    toc: true